run-tests: do not run as root.
It's bad hygiene, and also we rely on `chmod 0` to make files inaccessible,
root can still access them.

Closes #76.

diff --git a/devel/run-tests b/devel/run-tests
--- a/devel/run-tests
+++ b/devel/run-tests
@@ -11,6 +11,10 @@ if [ ! -e test.py ]; then
 	echo "fatal: can't find test.py. are you in the right directory?" >&2
 	exit 1
 fi
+if [[ "$(id -u)" = 0 ]]; then
+	echo "fatal: tests cannot be run as root" >&2
+	exit 1
+fi
 if [[ -z "$CC" ]]; then
   CC="$(which gcc)"
 fi
